server:
  port: 9696
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: rohit
    url: jdbc:postgresql://localhost:5432/health
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
